### PR TITLE
update README

### PR DESCRIPTION
**Pull request by pythonpete32**
since the app is only available on rinkeby, I added the `--environment aragon:rinkeby` flag to the `dao install` command. I also added the `dao acl create` commands required for the app to work properly.

### CODE REVIEW

**Comment by burrrata** [comment]
Cool. I'll test the deployment guide and add it into my PR to update the docs. Thanks! :)

**Comment by burrrata** [comment]
Got an error at this step: "Cannot find transaction path for executing action" 

`aragon dao install $dao redemptions.open.aragonpm.eth --app-init-args $vault $token --environment aragon:rinkeby`

**Comment by fabriziovigevani** [comment]
Must depend on you permissions setup. 
Who has the permission to manage apps? Is an account or is the voting app? 
In case is an account, are you using that account to install the app?

**Comment by burrrata** [comment]
The permissions were set so that the same account had the only voting token and was also the one that initialized the DAO and had all the default permissions. I'll try again in a bit and let you know if the same errors come up

**Pull request closed without merging**
