### PR TITLE
Redeemable token decimals

### LINKED ISSUE #29: Fix redeem functionality to handle tokens 18 decimal units
When trying to redeem tokens with a 18 decimal units the front broke

### PR DESCRIPTION
**Pull request by fabriziovigevani**
closes #29

### CODE REVIEW

**Comment by lkngtn** [comment]
Not sure why this change would cause this issue, but when I try and run using this branch I get the following:

image

**Comment by 0xGabi** [comment]
This was a change I made on master to publish the correct manifest.json.
The problem is that when we use it in local dev we need /dist/... paths

**Comment by lkngtn** [comment]
> This was a change I made on master to publish the correct manifest.json. The problem is that when we use it in local dev we need /dist/... paths El El mar, 4 de jun. de 2019 a las 17:56, Luke Duncan < notifications@github.com> escribió:
> […](#)

I wonder what the suggested workflow for dev-->deployment. Maybe we should have a deployment branch?

**Comment by fabriziovigevani** [comment]
Seems strange that when you `aragon run` the application, it publishes to your local  ipfs node, a tree file different that the one is published to production. 

I think in our case, the best approach should be to serve the application through http when in development, so we keep things unmodified in our project (manifest.json in this case). 

So when trying out the application in dev should be
`aragon run --template Template --template-init @ARAGON_ENS  --http localhost:8001 --http-served-from ./dist --reset`

**Comment by fabriziovigevani** [comment]
We realized we can specify which files we want to deploy to ipfs:   
`aragon run --template Template --template-init @ARAGON_ENS  --files ./dist`

**Pull request merged**
